### PR TITLE
New CTM to exclude BB7

### PR DESCRIPTION
**Pull request by adgad**
This will make Blackberry 7 also get the core experience (and still excludes Android < 4)

See 	http://kangax.github.io/compat-table/es5/#test-Function.prototype.bind
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_objects/Function/bind

### CODE REVIEW

**Comment by wheresrhys** [comment]
side effect is this will mean fewer iOS safari get enhanced (v6 cutoff now - was v5 before), but that’s probably ok. 0.3% of traffic

**Comment by wheresrhys** [comment]
It feels very nice to CTM based on a feature we actually use too

**Comment by adgad** [comment]
I'm taking that as a :+1:

**Comment by wheresrhys** [comment]
damn cheek

**Pull request merged**
