### PR TITLE
Use className, for IE compatibility

### PR DESCRIPTION
**Pull request by ironsidevsquincy**
rather than the cooler `classList`

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
Actually, `classList` seems to work fine with IE9, contrary to http://caniuse.com/#search=classList

**Comment by matthew-andrews** [comment]
also we have polyfill service

**Comment by matthew-andrews** [comment]
> contrary to http://caniuse.com/#search=classList
probably because of polyfill service

**Comment by ironsidevsquincy** [comment]
ahh, yes

**Pull request closed without merging**
