### PR TITLE
Load HTMLPictureElement polyfill

### PR DESCRIPTION
**Pull request by ironsidevsquincy**
And always load polyfill file, event if browsers doesn't CTM

cc: @tom-parker

### CODE REVIEW

**Comment by tom-parker** [comment]
:+1: 

Presumably we're ripping this out of `n-image` too?

**Comment by ironsidevsquincy** [comment]
https://github.com/Financial-Times/n-image/pull/9

**Comment by matthew-andrews** [comment]
does this mean images won't work without javascript, or have i misunderstood something?

**Comment by matthew-andrews** [comment]
would you mind helping me understand why we need to load polyfills even if browsers don't ctm?

**Comment by ironsidevsquincy** [comment]
If you set the `fallback` option in `n-image`, then images load without JS. This can, however, cause a double download of images, so in practice we don't set it.

Without the picture polyfill, non-ctm browsers were getting no images. This adds the HTMLPictureElement polyfill, and loads it on all browsers

**Pull request merged**
