### PR TITLE
Remove next-welcome

### PR DESCRIPTION
**Pull request by i-like-robots**
n-layout has taken the responsibility for these things: https://github.com/Financial-Times/n-layout

### CODE REVIEW

**Comment by wheresrhys** [comment]
ah, didn't realise this was a PR. Thought was just an issue. 

Does this need to be a major release? Or a minor but accompanied by a speedy roll out of n-layout? I'd prefer the later

**Comment by i-like-robots** [comment]
By the rules of semver I guess this is major as it potentially breaks stuff

**Comment by i-like-robots** [comment]
We could specify the n-js-setup dependency only in n-layout https://github.com/Financial-Times/next-article/pull/837/files#r37997148

**Comment by wheresrhys** [comment]
n-js-setup - nice. Though potentially using next-js-setup in bower.json will still pick it up as github tries to forward dead urls

> By the rules of semver I guess this is major as it potentially breaks stuff

I generally feel that that's the right attitude if you're publishing something where you don't know all the consumers, but when you're using it within your own team to manage releases then a more pragmatic looser approach is fine as long as you're clear on what the risks are

**Pull request merged**
