### PR TITLE
Adding stubs template

### PR DESCRIPTION
**Pull request by ironsidevsquincy**

### CODE REVIEW

**Comment by wheresrhys** [comment]
Why not include this in the js file itself?

**Comment by ironsidevsquincy** [comment]
In `next-js-setup.js`? Could do, but would need to go right at the top, before `require`s, so made sense to split it into a self-contained file and include separately

**Comment by ironsidevsquincy** [comment]
changed stubs to module

**Comment by wheresrhys** [comment]
:+1:

**Pull request merged**
